"""empty message

Revision ID: 4b0df3c20fc2
Revises: 
Create Date: 2021-03-05 18:44:32.075787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0df3c20fc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=5000), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nick_name', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user')
    # ### end Alembic commands ###
